---
swagger: "2.0"
info:
  description: "test-api"
  version: "1"
  title: "Test API"
paths:
  /api/test:
    post:
      description: "Do a thing"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/body"
        x-example: "{\n  \"test\":\"example\"\n}\n"
      responses:
        200:
          description: "Worked"
          examples:
            results:
            - id: 1
              type: "foo"
definitions:
  body:
    type: "object"
    properties:
      test:
        type: "string"
